[2024-08-01T14:36:37.186-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-01T14:36:37.197-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.get_weather scheduled__2024-07-30T06:00:00+00:00 [queued]>
[2024-08-01T14:36:37.200-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.get_weather scheduled__2024-07-30T06:00:00+00:00 [queued]>
[2024-08-01T14:36:37.200-0300] {taskinstance.py:2306} INFO - Starting attempt 6 of 6
[2024-08-01T14:36:37.208-0300] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): get_weather> on 2024-07-30 06:00:00+00:00
[2024-08-01T14:36:37.211-0300] {standard_task_runner.py:64} INFO - Started process 65883 to run task
[2024-08-01T14:36:37.213-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather_dag', 'get_weather', 'scheduled__2024-07-30T06:00:00+00:00', '--job-id', '193', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpa1kn2m7l']
[2024-08-01T14:36:37.214-0300] {standard_task_runner.py:91} INFO - Job 193: Subtask get_weather
[2024-08-01T14:36:37.235-0300] {task_command.py:426} INFO - Running <TaskInstance: weather_dag.get_weather scheduled__2024-07-30T06:00:00+00:00 [running]> on host BOOK-U1A3RU270O.
[2024-08-01T14:36:37.269-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='marceloc.bastos@hotmail.com' AIRFLOW_CTX_DAG_OWNER='Marcelo' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='get_weather' AIRFLOW_CTX_EXECUTION_DATE='2024-07-30T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-30T06:00:00+00:00'
[2024-08-01T14:36:37.270-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-01T14:36:37.270-0300] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-01T14:36:37.271-0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /home/mcb/code/marcelo7bastos/airflow/dags/src/get_weather.py']
[2024-08-01T14:36:37.276-0300] {subprocess.py:86} INFO - Output:
[2024-08-01T14:36:37.283-0300] {subprocess.py:93} INFO - python: can't open file '/home/mcb/code/marcelo7bastos/airflow/dags/src/get_weather.py': [Errno 2] No such file or directory
[2024-08-01T14:36:37.285-0300] {subprocess.py:97} INFO - Command exited with return code 2
[2024-08-01T14:36:37.285-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-01T14:36:37.289-0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/mcb/.pyenv/versions/venv_airflow_mda/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mcb/.pyenv/versions/venv_airflow_mda/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mcb/.pyenv/versions/venv_airflow_mda/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mcb/.pyenv/versions/venv_airflow_mda/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-08-01T14:36:37.291-0300] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=weather_dag, task_id=get_weather, run_id=scheduled__2024-07-30T06:00:00+00:00, execution_date=20240730T060000, start_date=20240801T173637, end_date=20240801T173637
[2024-08-01T14:36:37.299-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 193 for task get_weather (Bash command failed. The command returned a non-zero exit code 2.; 65883)
[2024-08-01T14:36:37.306-0300] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-01T14:36:37.315-0300] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-01T14:36:37.319-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
