[2024-08-01T14:26:22.685-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-01T14:26:22.697-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.get_weather manual__2024-08-01T17:25:14.018769+00:00 [queued]>
[2024-08-01T14:26:22.700-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.get_weather manual__2024-08-01T17:25:14.018769+00:00 [queued]>
[2024-08-01T14:26:22.700-0300] {taskinstance.py:2306} INFO - Starting attempt 2 of 6
[2024-08-01T14:26:22.709-0300] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): get_weather> on 2024-08-01 17:25:14.018769+00:00
[2024-08-01T14:26:22.711-0300] {standard_task_runner.py:64} INFO - Started process 55541 to run task
[2024-08-01T14:26:22.713-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather_dag', 'get_weather', 'manual__2024-08-01T17:25:14.018769+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpf15f6ube']
[2024-08-01T14:26:22.714-0300] {standard_task_runner.py:91} INFO - Job 24: Subtask get_weather
[2024-08-01T14:26:22.735-0300] {task_command.py:426} INFO - Running <TaskInstance: weather_dag.get_weather manual__2024-08-01T17:25:14.018769+00:00 [running]> on host BOOK-U1A3RU270O.
[2024-08-01T14:26:22.770-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='marceloc.bastos@hotmail.com' AIRFLOW_CTX_DAG_OWNER='Marcelo' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='get_weather' AIRFLOW_CTX_EXECUTION_DATE='2024-08-01T17:25:14.018769+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-01T17:25:14.018769+00:00'
[2024-08-01T14:26:22.771-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-01T14:26:22.771-0300] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-01T14:26:22.772-0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /home/mcb/code/marcelo7bastos/airflow/dags/src/get_weather.py']
[2024-08-01T14:26:22.777-0300] {subprocess.py:86} INFO - Output:
[2024-08-01T14:26:22.784-0300] {subprocess.py:93} INFO - python: can't open file '/home/mcb/code/marcelo7bastos/airflow/dags/src/get_weather.py': [Errno 2] No such file or directory
[2024-08-01T14:26:22.786-0300] {subprocess.py:97} INFO - Command exited with return code 2
[2024-08-01T14:26:22.786-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-01T14:26:22.790-0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/mcb/.pyenv/versions/venv_airflow_mda/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mcb/.pyenv/versions/venv_airflow_mda/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mcb/.pyenv/versions/venv_airflow_mda/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mcb/.pyenv/versions/venv_airflow_mda/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-08-01T14:26:22.792-0300] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_dag, task_id=get_weather, run_id=manual__2024-08-01T17:25:14.018769+00:00, execution_date=20240801T172514, start_date=20240801T172622, end_date=20240801T172622
[2024-08-01T14:26:22.798-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 24 for task get_weather (Bash command failed. The command returned a non-zero exit code 2.; 55541)
[2024-08-01T14:26:22.806-0300] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-01T14:26:22.815-0300] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-01T14:26:22.815-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
