[2024-08-01T16:13:31.060-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-01T16:13:31.072-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: new_dag_test_macelo.get_weather scheduled__2024-07-29T08:00:00+00:00 [queued]>
[2024-08-01T16:13:31.075-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: new_dag_test_macelo.get_weather scheduled__2024-07-29T08:00:00+00:00 [queued]>
[2024-08-01T16:13:31.075-0300] {taskinstance.py:2306} INFO - Starting attempt 6 of 6
[2024-08-01T16:13:31.085-0300] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): get_weather> on 2024-07-29 08:00:00+00:00
[2024-08-01T16:13:31.088-0300] {standard_task_runner.py:64} INFO - Started process 118083 to run task
[2024-08-01T16:13:31.090-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'new_dag_test_macelo', 'get_weather', 'scheduled__2024-07-29T08:00:00+00:00', '--job-id', '650', '--raw', '--subdir', 'DAGS_FOLDER/new_dag_test_macelo.py', '--cfg-path', '/tmp/tmp96nosbwl']
[2024-08-01T16:13:31.090-0300] {standard_task_runner.py:91} INFO - Job 650: Subtask get_weather
[2024-08-01T16:13:31.112-0300] {task_command.py:426} INFO - Running <TaskInstance: new_dag_test_macelo.get_weather scheduled__2024-07-29T08:00:00+00:00 [running]> on host BOOK-U1A3RU270O.
[2024-08-01T16:13:31.146-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='marceloc.bastos@hotmail.com' AIRFLOW_CTX_DAG_OWNER='Marcelo' AIRFLOW_CTX_DAG_ID='new_dag_test_macelo' AIRFLOW_CTX_TASK_ID='get_weather' AIRFLOW_CTX_EXECUTION_DATE='2024-07-29T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-29T08:00:00+00:00'
[2024-08-01T16:13:31.146-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-01T16:13:31.147-0300] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-01T16:13:31.147-0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /home/mcb/code/marcelo7bastos/airflow/dags/src/get_weather.py']
[2024-08-01T16:13:31.152-0300] {subprocess.py:86} INFO - Output:
[2024-08-01T16:13:31.160-0300] {subprocess.py:93} INFO - python: can't open file '/home/mcb/code/marcelo7bastos/airflow/dags/src/get_weather.py': [Errno 2] No such file or directory
[2024-08-01T16:13:31.161-0300] {subprocess.py:97} INFO - Command exited with return code 2
[2024-08-01T16:13:31.161-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-01T16:13:31.165-0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/mcb/.pyenv/versions/venv_airflow_mda/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mcb/.pyenv/versions/venv_airflow_mda/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mcb/.pyenv/versions/venv_airflow_mda/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mcb/.pyenv/versions/venv_airflow_mda/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-08-01T16:13:31.167-0300] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=new_dag_test_macelo, task_id=get_weather, run_id=scheduled__2024-07-29T08:00:00+00:00, execution_date=20240729T080000, start_date=20240801T191331, end_date=20240801T191331
[2024-08-01T16:13:31.174-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 650 for task get_weather (Bash command failed. The command returned a non-zero exit code 2.; 118083)
[2024-08-01T16:13:31.182-0300] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-01T16:13:31.192-0300] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-01T16:13:31.196-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
