[2024-08-01T14:37:46.123-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-01T14:37:46.136-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.get_weather scheduled__2024-07-30T09:00:00+00:00 [queued]>
[2024-08-01T14:37:46.139-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.get_weather scheduled__2024-07-30T09:00:00+00:00 [queued]>
[2024-08-01T14:37:46.139-0300] {taskinstance.py:2306} INFO - Starting attempt 2 of 6
[2024-08-01T14:37:46.148-0300] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): get_weather> on 2024-07-30 09:00:00+00:00
[2024-08-01T14:37:46.152-0300] {standard_task_runner.py:64} INFO - Started process 66929 to run task
[2024-08-01T14:37:46.153-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather_dag', 'get_weather', 'scheduled__2024-07-30T09:00:00+00:00', '--job-id', '212', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpitm5h2wo']
[2024-08-01T14:37:46.154-0300] {standard_task_runner.py:91} INFO - Job 212: Subtask get_weather
[2024-08-01T14:37:46.177-0300] {task_command.py:426} INFO - Running <TaskInstance: weather_dag.get_weather scheduled__2024-07-30T09:00:00+00:00 [running]> on host BOOK-U1A3RU270O.
[2024-08-01T14:37:46.210-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='marceloc.bastos@hotmail.com' AIRFLOW_CTX_DAG_OWNER='Marcelo' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='get_weather' AIRFLOW_CTX_EXECUTION_DATE='2024-07-30T09:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-30T09:00:00+00:00'
[2024-08-01T14:37:46.211-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-01T14:37:46.212-0300] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-01T14:37:46.212-0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /home/mcb/code/marcelo7bastos/airflow/dags/src/get_weather.py']
[2024-08-01T14:37:46.216-0300] {subprocess.py:86} INFO - Output:
[2024-08-01T14:37:46.225-0300] {subprocess.py:93} INFO - python: can't open file '/home/mcb/code/marcelo7bastos/airflow/dags/src/get_weather.py': [Errno 2] No such file or directory
[2024-08-01T14:37:46.226-0300] {subprocess.py:97} INFO - Command exited with return code 2
[2024-08-01T14:37:46.227-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-01T14:37:46.230-0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/mcb/.pyenv/versions/venv_airflow_mda/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mcb/.pyenv/versions/venv_airflow_mda/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mcb/.pyenv/versions/venv_airflow_mda/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mcb/.pyenv/versions/venv_airflow_mda/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-08-01T14:37:46.232-0300] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_dag, task_id=get_weather, run_id=scheduled__2024-07-30T09:00:00+00:00, execution_date=20240730T090000, start_date=20240801T173746, end_date=20240801T173746
[2024-08-01T14:37:46.240-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 212 for task get_weather (Bash command failed. The command returned a non-zero exit code 2.; 66929)
[2024-08-01T14:37:46.246-0300] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-01T14:37:46.257-0300] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-01T14:37:46.257-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
